require("plugins")
require("packui").setup()
require("configs")
require("lsp")
require("keymaps")
require("statusline")
require("autocmds")
require("umbraline")
require("sessions").setup()
require("cwd").setup({
    paths = {
        "~/personal",
        "~/prefapp",
        "~/pre-vieitesss",
        "~/firestartr-pre",
        "~/firestartr-pro",
        "~/.config",
    },
})
require("term").setup()
