_default:
	just -l

build feature="all":
	#!/usr/bin/env bash
	set -e

	function build() {
		# Relative path to the feature
		local f="$1"

		printf "Building $f..."
		go build -o "../bin/$f" "./$f"
		printf "\r✅ Built $f"
	}

	if [[ "{{feature}}" != "all" ]]
	then
		build "{{feature}}"
		exit 0
	fi

	for p in $(find . -type d -mindepth 1 -maxdepth 1)
	do 
		build $(basename "$p")
	done

